// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function GetCurrentVersion():Promise<string>;
